### ISSUE TITLE
Any help using jk

### ISSUE THREAD

**Issue by Alexplose** [sshoecraft/solardirector#2]
I'm trying to setup jk, so far I get it running with a first message in mqtt with status and config, then nothing after.

Do the .js script are required ? how to write them any tutorial or sample appreciated.

What are the vars included in the script, found agent and this, but they doesn't contains my BMS data.

Tried a jk variable, but not defined.

How do I found them ? here is my command line 

`sudo ./jk -d 10 -v  -m 192.168.1.13 -t bt,C8:47:8C:F6:63:51`

Maybe some other configuration files are needed.

Thanks

**Comment by sshoecraft** [comment]
Alex, I haven't updated this agent in a while - simply because I'm (currently) unable to update the bms settings (I can with the android app).   In fact, I don't currently have this BMS in my system right now.   I'll dig it out and hook it up to one of my battery packs today and then update this agent.

I've been using the JS scripts to actually format and publish the data.  It's a change from my previous design where everything was done using C.  By using JS I can update the script (and output) without having to recompile the program or restart the service.

What are you looking to do exactly?

**Comment by Alexplose** [comment]
I'd like to get all the bms data sent to mqtt, as I'm using homeassistant,
grafana & influxdb.
Only reading is required.
I'll change settings via app.

I also have a pip 5048 mg, that I can already poll.

I just need to get bms data.

Le sam. 19 févr. 2022 à 15:23, sshoecraft ***@***.***> a
écrit :

**Comment by sshoecraft** [comment]
OK I didn't have a lot of time to work on this over the weekend, but I got the JK agent working

By default it will use the C code to publish data.  If you want to use javascript, rename the pub.js.example script to pub.js.

I also added a -T option so you can have the data published to whatever topic you want

**Comment by Alexplose** [comment]
Wonderfull works like a charm, thanks for the update and for your time.

Regards,
